[34m[1mwandb[0m: [32m[41mERROR[0m wandb.Image needs the PIL package. To get it, run "pip install pillow".
Traceback (most recent call last):
  File "c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\Fashion_MNIST_dataset_images.py", line 30, in <module>
    fashion_MNIST()
  File "c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\Fashion_MNIST_dataset_images.py", line 29, in fashion_MNIST
    wandb.log({"Plot": [wandb.Image(img, caption=caption) for img, caption in zip(set_images, set_labels)]})
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\Fashion_MNIST_dataset_images.py", line 29, in <listcomp>
    wandb.log({"Plot": [wandb.Image(img, caption=caption) for img, caption in zip(set_images, set_labels)]})
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\.conda\Lib\site-packages\wandb\sdk\data_types\image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "C:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\.conda\Lib\site-packages\wandb\sdk\data_types\image.py", line 296, in _initialize_from_data
    pil_image = util.get_module(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\.conda\Lib\site-packages\wandb\util.py", line 251, in get_module
    raise wandb.Error(required)
wandb.errors.errors.Error: wandb.Image needs the PIL package. To get it, run "pip install pillow".
